apiVersion: apps/v1
kind: Deployment
metadata:
  name: gclasses-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gclasses
  template:
    metadata:
      labels:
        app: gclasses
    spec:
      containers:
      - name: gclasses
        image: my-dockerhub-username/gclasses:latest
        ports:
        - containerPort: 8002
        env:
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "postgres-classes"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "gclasses"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Passer@24"
---
apiVersion: v1
kind: Service
metadata:
  name: gclasses-service
spec:
  selector:
    app: gclasses
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8002
  type: ClusterIP
