apiVersion: apps/v1
kind: Deployment
metadata:
  name: gcours-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gcours
  template:
    metadata:
      labels:
        app: gcours
    spec:
      containers:
      - name: gcours
        image: my-dockerhub-username/gcours:latest
        ports:
        - containerPort: 8003
        env:
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "postgres-cours"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "gcours"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Passer@24"
---
apiVersion: v1
kind: Service
metadata:
  name: gcours-service
spec:
  selector:
    app: gcours
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8003
  type: ClusterIP
