apiVersion: apps/v1
kind: Deployment
metadata:
  name: getudiants-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: getudiants
  template:
    metadata:
      labels:
        app: getudiants
    spec:
      containers:
      - name: getudiants
        image: my-dockerhub-username/getudiants:latest
        ports:
        - containerPort: 8005
        env:
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "postgres-etudiants"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "getudiants"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Passer@24"
---
apiVersion: v1
kind: Service
metadata:
  name: getudiants-service
spec:
  selector:
    app: getudiants
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8005
  type: ClusterIP
