
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gprofs-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gprofs
  template:
    metadata:
      labels:
        app: gprofs
    spec:
      containers:
      - name: gprofs
        image: my-dockerhub-username/gprofs:latest
        ports:
        - containerPort: 8006
        env:
        - name: DB_CONNECTION
          value: "pgsql"
        - name: DB_HOST
          value: "postgres-profs"
        - name: DB_PORT
          value: "5432"
        - name: DB_DATABASE
          value: "gprofs"
        - name: DB_USERNAME
          value: "postgres"
        - name: DB_PASSWORD
          value: "Passer@24"
---
apiVersion: v1
kind: Service
metadata:
  name: gprofs-service
spec:
  selector:
    app: gprofs
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8006
  type: ClusterIP
