apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-cours-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-cours
  template:
    metadata:
      labels:
        app: postgres-cours
    spec:
      containers:
      - name: postgres-cours
        image: postgres:13
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "gcours"
        - name: POSTGRES_USER
          value: "postgres"
        - name: POSTGRES_PASSWORD
          value: "Passer@24"
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-cours-service
spec:
  selector:
    app: postgres-cours
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  type: ClusterIP
